name: vscode_for_android
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.5+7
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  archive: ^3.1.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_background: ^1.1.0
  flutter_pty:
    git: https://github.com/TerminalStudio/flutter_pty
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  settings:
    git: https://github.com/nightmare-space/settings
  xterm: ^2.6.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/
